name: scheduled run

on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Pulling code from remote repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install newman and htmlextra reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Runs a set of commands using the runners shell
      - name: Run tests and reporting
        run: 'newman run Trello_Anna.postman_collection.json -e Trello_Enviroment_Anna.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export Trello_report.html'

      # Проверка создания файла
      - name: Check report file
        run: 'ls'

      # Прикрепляется ли артифакт к тестовому прогону
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Trello report
          path: "*html"
             
