name: scheduled run

on:
  schedule:
    - cron: 30 15 * * 5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Pulling code from remote repository
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install newman and htmlextra reporter
        run:    
          npm install -g newman
          ваш скрипт

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: 
          newman run 
